from django.urls import path

from apps.procurement.views import (
	ContractAmendmentCreateView,
	ContractAmendmentDetailView,
	ContractAmendmentListView,
	ContractAmendmentUpdateView,
    ContractBudgetApproveView,
    ContractBudgetBatchView,
    ContractBudgetDetailView,
    ContractBudgetListView,
    FulfillmentMemoApproveView,
	FulfillmentMemoCreateView,
	FulfillmentMemoListView,
	FulfillmentMemoUpdateView,
    PaymentCancelView,
	PaymentCreateView,
	PaymentListView,
	PaymentReportView,
	PaymentPostView,
	PaymentUpdateView,
    budget_orders_options,
	contract_financial_codes,
	contract_lines_options,
    contract_line_options,
	contract_orders_options,
	contract_suppliers,
	create_application_scope,
	order_budgets_options,
    order_lines_options,
	PurchaseOrderCancelView,
	PurchaseOrderCreateView,
	PurchaseOrderDeleteView,
	PurchaseOrderListView,
	PurchaseOrderUpdateView,
)

app_name = "procurement"

urlpatterns = [
	path("amendments/", ContractAmendmentListView.as_view(), name="amendment_list"),
	path("amendments/add/", ContractAmendmentCreateView.as_view(), name="amendment_create"),
	path("amendments/<int:pk>/detail/", ContractAmendmentDetailView.as_view(), name="amendment_detail"),
	path("amendments/<int:pk>/edit/", ContractAmendmentUpdateView.as_view(), name="amendment_update"),
	path("orders/", PurchaseOrderListView.as_view(), name="order_list"),
	path("orders/add/", PurchaseOrderCreateView.as_view(), name="order_create"),
	path("orders/<int:pk>/edit/", PurchaseOrderUpdateView.as_view(), name="order_update"),
	path("orders/<int:pk>/delete/", PurchaseOrderDeleteView.as_view(), name="order_delete"),
	path("orders/<int:pk>/cancel/", PurchaseOrderCancelView.as_view(), name="order_cancel"),
	path("budgets/", ContractBudgetListView.as_view(), name="budget_list"),
	path("budgets/add/", ContractBudgetBatchView.as_view(), name="budget_create"),
	path("budgets/contract/<str:contract_id>/", ContractBudgetBatchView.as_view(), name="budget_batch"),
	path("budgets/<int:pk>/detail/", ContractBudgetDetailView.as_view(), name="budget_detail"),
	path("budgets/<int:pk>/approve/", ContractBudgetApproveView.as_view(), name="budget_approve"),
	path("memos/", FulfillmentMemoListView.as_view(), name="memo_list"),
	path("memos/add/", FulfillmentMemoCreateView.as_view(), name="memo_create"),
	path("memos/<int:pk>/edit/", FulfillmentMemoUpdateView.as_view(), name="memo_update"),
	path("memos/<int:pk>/approve/", FulfillmentMemoApproveView.as_view(), name="memo_approve"),
	path("payments/", PaymentListView.as_view(), name="payment_list"),
	path("payments/add/", PaymentCreateView.as_view(), name="payment_create"),
	path("payments/<int:pk>/report/", PaymentReportView.as_view(), name="payment_report"),
	path("payments/<int:pk>/edit/", PaymentUpdateView.as_view(), name="payment_update"),
	path("payments/<int:pk>/post/", PaymentPostView.as_view(), name="payment_post"),
	path("payments/<int:pk>/cancel/", PaymentCancelView.as_view(), name="payment_cancel"),
	path("api/contracts/<str:contract_id>/line-options/", contract_line_options, name="contract_line_options"),
	path("api/contracts/<str:contract_id>/lines-options/", contract_lines_options, name="contract_lines_options"),
	path("api/contracts/<str:contract_id>/suppliers/", contract_suppliers, name="contract_suppliers"),
	path("api/contracts/<str:contract_id>/financial-codes/", contract_financial_codes, name="contract_financial_codes"),
	path("api/contracts/<str:contract_id>/orders-options/", contract_orders_options, name="contract_orders_options"),
	path("api/orders/<int:order_id>/lines-options/", order_lines_options, name="order_lines_options"),
	path("api/orders/<int:order_id>/budgets-options/", order_budgets_options, name="order_budgets_options"),
	path("api/budgets/<int:budget_id>/orders-options/", budget_orders_options, name="budget_orders_options"),
	path("api/application-scopes/create/", create_application_scope, name="application_scope_create"),
]